name: Rhizome Labs
url: http://labs.rhizome.org 
description: "unrestricted experimentation"

paginate: 5
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
timezone: America/New_York
excerpt_separator: <!--more-->
