name: Rhizome Labs
url: http://labs.rhizome.org 
description: "A byproduct of Rhizome.org, a collection of insights on software development, a resource for technologists working in arts and cultural institutions."

paginate: 5
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
timezone: America/New_York
excerpt_separator: <!--more-->
