name: Rhizome Labs
url: http://localhost:4000
description: "Rhizome developer blog" 

paginate: 5
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
timezone: America/New_York
org: Rhizome
excerpt_separator: <!--more-->
